name: Run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your code

    - name: Set up JDK 21
      uses: actions/setup-java@v3 # Action to set up the Java environment
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'gradle' # Caches Gradle dependencies to speed up builds

    - name: Make gradlew executable
      run: chmod +x ./gradlew # Ensure the Gradle wrapper script is executable

    - name: Build debug APK
      run: ./gradlew assembleDebug # Run the Gradle task to build the APK

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4 # Action to save the built APK as an artifact
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Generate version info
      id: version
      run: |
        VERSION_CODE=$(date +%s)
        VERSION_NAME="${{ github.event.inputs.buildType }}-${{ github.ref_name }}-$(date +%Y%m%d)"
        echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        echo "versionCode=$VERSION_CODE" >> $GITHUB_OUTPUT
        echo "versionName=$VERSION_NAME" >> $GITHUB_OUTPUT      

    - name: Build debug APK
      run: |
        ./gradlew assembleDebug\
        -PversionCode=$VERSION_CODE \

    - name: Send Debug APK to Telegram
      run: |
        APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
        COMMIT_MSG=$(git log -1 --pretty=%B)
        
        curl -v -F "chat_id=$TELEGRAM_CHAT_ID" \
             -F "document=@$APK_PATH" \
             -F "caption=ðŸš€ *New Build Ready!*%0A%0A*Commit:* $COMMIT_MSG%0A*Branch:* ${{ github.ref_name }}" \
             -F "parse_mode=Markdown" \
             "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }}/sendDocument